# Generated by Django 3.0.2 on 2020-04-19 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Agendas',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horas',
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=255, unique=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especialidades', to='api.Especialidades')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_agendamento', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 20, 56, 24, 692459, tzinfo=utc), editable=False)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agendas', to='api.Agendas')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Horas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.AddField(
            model_name='agendas',
            name='horario',
            field=models.ManyToManyField(to='api.Horas'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicos', to='api.Medicos'),
        ),
        migrations.AlterUniqueTogether(
            name='agendas',
            unique_together={('dia', 'medico')},
        ),
    ]
