# Generated by Django 3.0.5 on 2020-04-22 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Agendas',
                'ordering': ['dia'],
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crm', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=255, unique=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especialidades', to='api.Especialidades')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('horario', models.DateField()),
                ('data_agendamento', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 23, 17, 7, 890513, tzinfo=utc), editable=False)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agendas', to='api.Agendas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.AddField(
            model_name='agendas',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicos', to='api.Medicos'),
        ),
        migrations.AlterUniqueTogether(
            name='agendas',
            unique_together={('dia', 'medico')},
        ),
        migrations.CreateModel(
            name='AgendaHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('disponivel', models.BooleanField(default=True, editable=False, verbose_name='disponível')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='api.Agendas')),
            ],
            options={
                'verbose_name': 'Horário',
                'ordering': ['hora'],
                'unique_together': {('agenda', 'hora')},
            },
        ),
    ]
