# Generated by Django 2.2.10 on 2020-04-12 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 23, 51, 3, 177731, tzinfo=utc), editable=False),
        ),
    ]
