# Generated by Django 3.0.5 on 2020-04-22 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 23, 17, 26, 735782, tzinfo=utc), editable=False),
        ),
    ]
