# Generated by Django 3.0.5 on 2020-04-22 23:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200422_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 23, 20, 48, 547041, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='horario',
            field=models.TimeField(),
        ),
    ]
