# Generated by Django 2.2.10 on 2020-04-13 04:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200413_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 13, 4, 12, 28, 852814, tzinfo=utc), editable=False),
        ),
    ]
